import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const currentDir = dirname(fileURLToPath(import.meta.url))
const router = readFileSync(join(currentDir, '../router/index.js'), 'utf8')
const workspace = readFileSync(join(currentDir, 'ai-recommend-v2/AiRecommendV2Workspace.vue'), 'utf8')
const profile = readFileSync(join(currentDir, 'ai-recommend-v2/components/ProfileSidebar.vue'), 'utf8')
const chat = readFileSync(join(currentDir, 'ai-recommend-v2/components/AiChatMiniPanel.vue'), 'utf8')
const candidates = readFileSync(join(currentDir, 'ai-recommend-v2/components/DraftPanel.vue'), 'utf8')
const reportView = readFileSync(join(currentDir, 'ai-recommend-v2/components/ReportView.vue'), 'utf8')
const reportDocument = readFileSync(join(currentDir, 'ai-recommend-v2/components/report/ReportDocument.vue'), 'utf8')
const reportCandidate = readFileSync(join(currentDir, 'ai-recommend-v2/components/report/ReportCandidateCard.vue'), 'utf8')

assert.match(router, /component:\s*\(\)\s*=>\s*import\('@\/views\/ai-recommend-v2\/AiRecommendV2Workspace\.vue'\)/)
assert.match(router, /path:\s*'\/ai-report-v2\/:id'/)
assert.match(router, /component:\s*\(\)\s*=>\s*import\('@\/views\/ai-recommend-v2\/components\/ReportView\.vue'\)/)
assert.match(workspace, /class="hero-status-strip"/)
assert.match(workspace, /class="chat-panel-frame"/)
assert.match(workspace, /class="ai-workflow-strip"/)
assert.match(workspace, /class="workflow-step"/)
assert.match(workspace, /候选分析与追问/)
assert.match(workspace, /grid-template-columns:\s*300px minmax\(560px, 1fr\) 480px/)
assert.match(workspace, /\.prototype-page\s*{[\s\S]*height:\s*100vh[\s\S]*overflow:\s*hidden/)
assert.match(workspace, /\.v2-wrap\s*{[\s\S]*flex:\s*1[\s\S]*overflow:\s*hidden/)
assert.match(workspace, /\.main-grid\s*{[\s\S]*flex:\s*1[\s\S]*height:\s*auto[\s\S]*overflow:\s*hidden/)
assert.match(workspace, /\.left-col :deep\(\.profile-card\)\s*{[\s\S]*flex:\s*1[\s\S]*overflow-y:\s*auto/)
assert.match(workspace, /const chatVisible = ref\(true\)/)
assert.match(workspace, /function sanitizeAssistantText/)
assert.match(workspace, /chatStreamingText\.value = sanitizeAssistantText\(assistantText\)/)
assert.match(workspace, /content: sanitizeAssistantText\(data\.message\)/)
assert.match(workspace, /\.center-col\s*{[\s\S]*display:\s*flex[\s\S]*flex-direction:\s*column/)
assert.match(workspace, /\.ai-workflow-strip\s*{[\s\S]*flex-shrink:\s*0/)
assert.match(workspace, /\.chat-panel-frame\s*{[\s\S]*flex:\s*1[\s\S]*height:\s*auto/)
assert.match(profile, /class="score-panel"/)
assert.match(profile, /PUBLIC_REGULAR/)
assert.match(profile, /普通本科/)
assert.match(chat, /\.chat-mini\s*{[\s\S]*height:\s*100%/)
assert.match(chat, /class="chat-expanded"/)
assert.doesNotMatch(chat, /chat-collapsed/)
assert.doesNotMatch(chat, /问 AI 关于草稿的问题/)
assert.match(chat, /\.chat-input-row\s*{[\s\S]*flex-shrink:\s*0/)
assert.match(candidates, /\.draft-panel\s*{[\s\S]*height:\s*100%/)
assert.match(candidates, /class="draft-steps"/)
assert.match(candidates, /class="tier-tabs"/)
assert.match(candidates, /class="tier-list-shell"/)
assert.match(candidates, /class="report-action-bar"/)
assert.match(candidates, /position:\s*sticky/)
assert.match(candidates, /\.report-action-bar\s*{[\s\S]*flex-shrink:\s*0/)
assert.match(candidates, /overflow-x:\s*hidden/)
assert.match(candidates, /flex-wrap:\s*wrap/)
assert.match(reportView, /import ReportDocument from '\.\/report\/ReportDocument\.vue'/)
assert.match(reportView, /<ReportDocument/)
assert.doesNotMatch(reportView, /DraftCandidateCard/)
assert.match(reportDocument, /<ReportCover/)
assert.match(reportDocument, /<ReportExecutiveSummary/)
assert.match(reportDocument, /<ReportProfileBasis/)
assert.match(reportDocument, /<ReportTierSection/)
assert.match(reportDocument, /<ReportDataNotice/)
assert.match(reportCandidate, /const fact = computed\(\(\) => props\.candidate\?\.fact \|\| \{\}\)/)
assert.match(reportCandidate, /const opinion = computed\(\(\) => props\.candidate\?\.opinion \|\| \{\}\)/)
assert.doesNotMatch(reportCandidate, /问 AI|移出草稿|replace|remove/)

console.log('AiRecommend layout checks passed')
