-- Pollution cleanup for postgrad_selector.
-- Date: 2026-06-13
-- Scope:
--   1. Remove admission rows without source_id. These rows are outside the N诺-only workspace/recommendation scope.
--   2. Remove year=0 quality rows generated by invalid imported admission_score rows.
--   3. Remove unreferenced third-party data_source rows whose source_owner is NULL.
--   4. Rebuild program_year_data_quality flags from current N诺 admissions data.
--
-- Run this file only after reviewing the dry-run counts below.
-- The cleanup creates backup tables first. Do not drop backup tables until the UI and recommendation results are verified.

SET @cleanup_tag := '20260613_polluted_data';

-- ---------------------------------------------------------------------------
-- 0. Dry-run counts
-- ---------------------------------------------------------------------------

SELECT 'admission_score_source_id_null' AS item, COUNT(*) AS rows_count
FROM admission_score
WHERE source_id IS NULL;

SELECT 'admission_plan_source_id_null' AS item, COUNT(*) AS rows_count
FROM admission_plan
WHERE source_id IS NULL;

SELECT 'admission_result_source_id_null' AS item, COUNT(*) AS rows_count
FROM admission_result
WHERE source_id IS NULL;

SELECT 'quality_year_0' AS item, COUNT(*) AS rows_count
FROM program_year_data_quality
WHERE year = 0;

SELECT 'orphan_null_owner_third_party_source' AS item, COUNT(*) AS rows_count
FROM data_source ds
LEFT JOIN admission_score sc ON sc.source_id = ds.id
LEFT JOIN admission_plan ap ON ap.source_id = ds.id
LEFT JOIN admission_result ar ON ar.source_id = ds.id
WHERE ds.source_owner IS NULL
  AND ds.source_type = 'THIRD_PARTY'
  AND sc.id IS NULL
  AND ap.id IS NULL
  AND ar.id IS NULL;

-- ---------------------------------------------------------------------------
-- 1. Back up rows that will be removed
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS cleanup_backup_20260613_admission_score_source_null AS
SELECT * FROM admission_score WHERE source_id IS NULL;

CREATE TABLE IF NOT EXISTS cleanup_backup_20260613_admission_plan_source_null AS
SELECT * FROM admission_plan WHERE source_id IS NULL;

CREATE TABLE IF NOT EXISTS cleanup_backup_20260613_admission_result_source_null AS
SELECT * FROM admission_result WHERE source_id IS NULL;

CREATE TABLE IF NOT EXISTS cleanup_backup_20260613_quality_year_0 AS
SELECT * FROM program_year_data_quality WHERE year = 0;

CREATE TABLE IF NOT EXISTS cleanup_backup_20260613_data_source_null_owner_orphan AS
SELECT ds.*
FROM data_source ds
LEFT JOIN admission_score sc ON sc.source_id = ds.id
LEFT JOIN admission_plan ap ON ap.source_id = ds.id
LEFT JOIN admission_result ar ON ar.source_id = ds.id
WHERE ds.source_owner IS NULL
  AND ds.source_type = 'THIRD_PARTY'
  AND sc.id IS NULL
  AND ap.id IS NULL
  AND ar.id IS NULL;

-- ---------------------------------------------------------------------------
-- 2. Delete polluted rows
-- ---------------------------------------------------------------------------

DELETE FROM admission_score
WHERE source_id IS NULL;

DELETE FROM admission_plan
WHERE source_id IS NULL;

DELETE FROM admission_result
WHERE source_id IS NULL;

DELETE FROM program_year_data_quality
WHERE year = 0;

DELETE ds
FROM data_source ds
LEFT JOIN admission_score sc ON sc.source_id = ds.id
LEFT JOIN admission_plan ap ON ap.source_id = ds.id
LEFT JOIN admission_result ar ON ar.source_id = ds.id
WHERE ds.source_owner IS NULL
  AND ds.source_type = 'THIRD_PARTY'
  AND sc.id IS NULL
  AND ap.id IS NULL
  AND ar.id IS NULL;

-- ---------------------------------------------------------------------------
-- 3. Rebuild quality flags from N诺 data
-- ---------------------------------------------------------------------------

UPDATE program_year_data_quality q
LEFT JOIN (
  SELECT DISTINCT sc.program_id, sc.year
  FROM admission_score sc
  JOIN data_source ds ON ds.id = sc.source_id
  WHERE ds.source_owner LIKE 'N诺%'
) ns ON ns.program_id = q.program_id AND ns.year = q.year
LEFT JOIN (
  SELECT DISTINCT ap.program_id, ap.year
  FROM admission_plan ap
  JOIN data_source ds ON ds.id = ap.source_id
  WHERE ds.source_owner LIKE 'N诺%'
) np ON np.program_id = q.program_id AND np.year = q.year
LEFT JOIN (
  SELECT DISTINCT ar.program_id, ar.year
  FROM admission_result ar
  JOIN data_source ds ON ds.id = ar.source_id
  WHERE ds.source_owner LIKE 'N诺%'
) nr ON nr.program_id = q.program_id AND nr.year = q.year
SET
  q.has_score = IF(ns.program_id IS NULL, 0, 1),
  q.has_plan = IF(np.program_id IS NULL, 0, 1),
  q.has_result = IF(nr.program_id IS NULL, 0, 1),
  q.has_official_source = 0,
  q.completeness_level = CASE
    WHEN ns.program_id IS NOT NULL AND np.program_id IS NOT NULL AND nr.program_id IS NOT NULL THEN 'A'
    WHEN (ns.program_id IS NOT NULL AND np.program_id IS NOT NULL)
      OR (ns.program_id IS NOT NULL AND nr.program_id IS NOT NULL)
      OR (np.program_id IS NOT NULL AND nr.program_id IS NOT NULL) THEN 'B'
    WHEN ns.program_id IS NOT NULL OR np.program_id IS NOT NULL OR nr.program_id IS NOT NULL THEN 'C'
    ELSE 'D'
  END,
  q.missing_fields = CASE
    WHEN ns.program_id IS NOT NULL AND np.program_id IS NOT NULL AND nr.program_id IS NOT NULL THEN JSON_ARRAY()
    WHEN ns.program_id IS NULL AND np.program_id IS NOT NULL AND nr.program_id IS NOT NULL THEN JSON_ARRAY('score')
    WHEN ns.program_id IS NOT NULL AND np.program_id IS NULL AND nr.program_id IS NOT NULL THEN JSON_ARRAY('plan')
    WHEN ns.program_id IS NOT NULL AND np.program_id IS NOT NULL AND nr.program_id IS NULL THEN JSON_ARRAY('result')
    WHEN ns.program_id IS NULL AND np.program_id IS NULL AND nr.program_id IS NOT NULL THEN JSON_ARRAY('score', 'plan')
    WHEN ns.program_id IS NULL AND np.program_id IS NOT NULL AND nr.program_id IS NULL THEN JSON_ARRAY('score', 'result')
    WHEN ns.program_id IS NOT NULL AND np.program_id IS NULL AND nr.program_id IS NULL THEN JSON_ARRAY('plan', 'result')
    ELSE JSON_ARRAY('score', 'plan', 'result')
  END,
  q.last_checked_at = CURRENT_TIMESTAMP;

-- ---------------------------------------------------------------------------
-- 4. Post-clean verification
-- ---------------------------------------------------------------------------

SELECT 'admission_score_source_id_null_after' AS item, COUNT(*) AS rows_count
FROM admission_score
WHERE source_id IS NULL;

SELECT 'admission_plan_source_id_null_after' AS item, COUNT(*) AS rows_count
FROM admission_plan
WHERE source_id IS NULL;

SELECT 'admission_result_source_id_null_after' AS item, COUNT(*) AS rows_count
FROM admission_result
WHERE source_id IS NULL;

SELECT 'quality_year_0_after' AS item, COUNT(*) AS rows_count
FROM program_year_data_quality
WHERE year = 0;

SELECT 'orphan_null_owner_third_party_source_after' AS item, COUNT(*) AS rows_count
FROM data_source ds
LEFT JOIN admission_score sc ON sc.source_id = ds.id
LEFT JOIN admission_plan ap ON ap.source_id = ds.id
LEFT JOIN admission_result ar ON ar.source_id = ds.id
WHERE ds.source_owner IS NULL
  AND ds.source_type = 'THIRD_PARTY'
  AND sc.id IS NULL
  AND ap.id IS NULL
  AND ar.id IS NULL;
